// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(StockCarniceriaContext))]
    [Migration("20251124153800_DatosSemilla")]
    partial class DatosSemilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Carnes Rojas"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Carnes Blancas"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Embutidos"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Nombre = "Mariscos"
                        });
                });

            modelBuilder.Entity("Service.Models.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdDetalleCompra")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DetallesCompra");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 100m,
                            FechaCompra = new DateTime(2025, 10, 25, 12, 37, 57, 449, DateTimeKind.Local).AddTicks(8646),
                            IdCompra = 5001,
                            IdDetalleCompra = 1,
                            IsDeleted = false,
                            PrecioUnitario = 18.00m,
                            ProductoId = 1,
                            ProveedorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 150m,
                            FechaCompra = new DateTime(2025, 10, 27, 12, 37, 57, 449, DateTimeKind.Local).AddTicks(8655),
                            IdCompra = 5002,
                            IdDetalleCompra = 2,
                            IsDeleted = false,
                            PrecioUnitario = 6.50m,
                            ProductoId = 4,
                            ProveedorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 80m,
                            FechaCompra = new DateTime(2025, 10, 30, 12, 37, 57, 449, DateTimeKind.Local).AddTicks(8659),
                            IdCompra = 5003,
                            IdDetalleCompra = 3,
                            IsDeleted = false,
                            PrecioUnitario = 16.00m,
                            ProductoId = 7,
                            ProveedorId = 4
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 50m,
                            FechaCompra = new DateTime(2025, 11, 4, 12, 37, 57, 449, DateTimeKind.Local).AddTicks(8664),
                            IdCompra = 5004,
                            IdDetalleCompra = 4,
                            IsDeleted = false,
                            PrecioUnitario = 20.00m,
                            ProductoId = 10,
                            ProveedorId = 3
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 120m,
                            FechaCompra = new DateTime(2025, 11, 9, 12, 37, 57, 449, DateTimeKind.Local).AddTicks(8668),
                            IdCompra = 5005,
                            IdDetalleCompra = 5,
                            IsDeleted = false,
                            PrecioUnitario = 11.50m,
                            ProductoId = 3,
                            ProveedorId = 2
                        },
                        new
                        {
                            Id = 6,
                            Cantidad = 100m,
                            FechaCompra = new DateTime(2025, 11, 14, 12, 37, 57, 449, DateTimeKind.Local).AddTicks(8672),
                            IdCompra = 5006,
                            IdDetalleCompra = 6,
                            IsDeleted = false,
                            PrecioUnitario = 8.50m,
                            ProductoId = 12,
                            ProveedorId = 3
                        });
                });

            modelBuilder.Entity("Service.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("IdDetalleVenta")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DetallesVenta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 2m,
                            IdDetalleVenta = 1,
                            IsDeleted = false,
                            PrecioUnitario = 25.50m,
                            ProductoId = 1,
                            VentaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 2m,
                            IdDetalleVenta = 2,
                            IsDeleted = false,
                            PrecioUnitario = 9.50m,
                            ProductoId = 4,
                            VentaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 1m,
                            IdDetalleVenta = 3,
                            IsDeleted = false,
                            PrecioUnitario = 15.99m,
                            ProductoId = 3,
                            VentaId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 2m,
                            IdDetalleVenta = 4,
                            IsDeleted = false,
                            PrecioUnitario = 22.00m,
                            ProductoId = 7,
                            VentaId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 2m,
                            IdDetalleVenta = 5,
                            IsDeleted = false,
                            PrecioUnitario = 28.00m,
                            ProductoId = 10,
                            VentaId = 3
                        },
                        new
                        {
                            Id = 6,
                            Cantidad = 3m,
                            IdDetalleVenta = 6,
                            IsDeleted = false,
                            PrecioUnitario = 7.99m,
                            ProductoId = 5,
                            VentaId = 3
                        },
                        new
                        {
                            Id = 7,
                            Cantidad = 1.5m,
                            IdDetalleVenta = 7,
                            IsDeleted = false,
                            PrecioUnitario = 14.50m,
                            ProductoId = 8,
                            VentaId = 4
                        },
                        new
                        {
                            Id = 8,
                            Cantidad = 2m,
                            IdDetalleVenta = 8,
                            IsDeleted = false,
                            PrecioUnitario = 11.99m,
                            ProductoId = 12,
                            VentaId = 4
                        });
                });

            modelBuilder.Entity("Service.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            IsDeleted = false,
                            Nombre = "Carne de Res - Corte Premium",
                            Precio = 25.50m,
                            Stock = 50,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            IsDeleted = false,
                            Nombre = "Carne de Res - Costilla",
                            Precio = 18.75m,
                            Stock = 35,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            IsDeleted = false,
                            Nombre = "Carne Molida de Res",
                            Precio = 15.99m,
                            Stock = 60,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 2,
                            IsDeleted = false,
                            Nombre = "Pechuga de Pollo",
                            Precio = 9.50m,
                            Stock = 80,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            IsDeleted = false,
                            Nombre = "Muslo de Pollo",
                            Precio = 7.99m,
                            Stock = 75,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            IsDeleted = false,
                            Nombre = "Filete de Pescado",
                            Precio = 16.50m,
                            Stock = 40,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 3,
                            IsDeleted = false,
                            Nombre = "Jamón Serrano",
                            Precio = 22.00m,
                            Stock = 30,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 3,
                            IsDeleted = false,
                            Nombre = "Chorizo Español",
                            Precio = 14.50m,
                            Stock = 25,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 3,
                            IsDeleted = false,
                            Nombre = "Salchicha Premium",
                            Precio = 12.75m,
                            Stock = 45,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 4,
                            IsDeleted = false,
                            Nombre = "Camarón Fresco",
                            Precio = 28.00m,
                            Stock = 20,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 4,
                            IsDeleted = false,
                            Nombre = "Pulpo Gallego",
                            Precio = 32.50m,
                            Stock = 15,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 4,
                            IsDeleted = false,
                            Nombre = "Mejillones Frescos",
                            Precio = 11.99m,
                            Stock = 50,
                            Unidad = "kg"
                        });
                });

            modelBuilder.Entity("Service.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Ganadería Premium S.A."
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Distribuidora de Carnes del Sur"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Mariscos Frescos Ltda."
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Nombre = "Embutidos Artesanales"
                        });
                });

            modelBuilder.Entity("Service.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@carniceria.com",
                            IsDeleted = false,
                            Nombre = "Admin Carnicería",
                            Password = "hashed_password_admin",
                            Rol = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "juan@carniceria.com",
                            IsDeleted = false,
                            Nombre = "Juan Vendedor",
                            Password = "hashed_password_vendedor",
                            Rol = "vendedor"
                        },
                        new
                        {
                            Id = 3,
                            Email = "maria@carniceria.com",
                            IsDeleted = false,
                            Nombre = "María Vendedora",
                            Password = "hashed_password_vendedor2",
                            Rol = "vendedor"
                        });
                });

            modelBuilder.Entity("Service.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TipoPagoEnum")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cliente = "Juan Pérez",
                            Fecha = new DateTime(2025, 11, 17, 12, 37, 57, 449, DateTimeKind.Local).AddTicks(8444),
                            IdVenta = 1001,
                            IsDeleted = false,
                            Precio = 76.50m,
                            TipoPagoEnum = 1,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            Cliente = "María García",
                            Fecha = new DateTime(2025, 11, 19, 12, 37, 57, 449, DateTimeKind.Local).AddTicks(8471),
                            IdVenta = 1002,
                            IsDeleted = false,
                            Precio = 57.49m,
                            TipoPagoEnum = 2,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 3,
                            Cliente = "Carlos López",
                            Fecha = new DateTime(2025, 11, 22, 12, 37, 57, 449, DateTimeKind.Local).AddTicks(8476),
                            IdVenta = 1003,
                            IsDeleted = false,
                            Precio = 94.99m,
                            TipoPagoEnum = 3,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cliente = "Ana Martínez",
                            Fecha = new DateTime(2025, 11, 23, 12, 37, 57, 449, DateTimeKind.Local).AddTicks(8480),
                            IdVenta = 1004,
                            IsDeleted = false,
                            Precio = 45.75m,
                            TipoPagoEnum = 4,
                            UsuarioId = 3
                        });
                });

            modelBuilder.Entity("Service.Models.Producto", b =>
                {
                    b.HasOne("Service.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Service.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
