// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(StockCarniceriaContext))]
    [Migration("20251126002206_DatosSemilla")]
    partial class DatosSemilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Carnes Rojas"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Aves y Pescados"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Embutidos"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Nombre = "Mariscos"
                        });
                });

            modelBuilder.Entity("Service.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadProductoVendido")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PrecioTotalProductoVendido")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVenta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadProductoVendido = 2m,
                            IsDeleted = false,
                            PrecioTotalProductoVendido = 51.00m,
                            ProductoId = 1,
                            VentaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CantidadProductoVendido = 2.5m,
                            IsDeleted = false,
                            PrecioTotalProductoVendido = 23.75m,
                            ProductoId = 4,
                            VentaId = 1
                        },
                        new
                        {
                            Id = 3,
                            CantidadProductoVendido = 1m,
                            IsDeleted = false,
                            PrecioTotalProductoVendido = 15.99m,
                            ProductoId = 3,
                            VentaId = 2
                        },
                        new
                        {
                            Id = 4,
                            CantidadProductoVendido = 1.5m,
                            IsDeleted = false,
                            PrecioTotalProductoVendido = 33.00m,
                            ProductoId = 7,
                            VentaId = 2
                        },
                        new
                        {
                            Id = 5,
                            CantidadProductoVendido = 2m,
                            IsDeleted = false,
                            PrecioTotalProductoVendido = 56.00m,
                            ProductoId = 10,
                            VentaId = 3
                        },
                        new
                        {
                            Id = 6,
                            CantidadProductoVendido = 3m,
                            IsDeleted = false,
                            PrecioTotalProductoVendido = 23.97m,
                            ProductoId = 5,
                            VentaId = 3
                        },
                        new
                        {
                            Id = 7,
                            CantidadProductoVendido = 1m,
                            IsDeleted = false,
                            PrecioTotalProductoVendido = 14.50m,
                            ProductoId = 8,
                            VentaId = 4
                        },
                        new
                        {
                            Id = 8,
                            CantidadProductoVendido = 2m,
                            IsDeleted = false,
                            PrecioTotalProductoVendido = 23.98m,
                            ProductoId = 12,
                            VentaId = 4
                        });
                });

            modelBuilder.Entity("Service.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            IsDeleted = false,
                            Nombre = "Carne de Res - Corte Premium",
                            PrecioUnitario = 25.50m,
                            ProveedorId = 1,
                            Stock = 50,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            IsDeleted = false,
                            Nombre = "Carne de Res - Costilla",
                            PrecioUnitario = 18.75m,
                            ProveedorId = 1,
                            Stock = 35,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            IsDeleted = false,
                            Nombre = "Carne Molida de Res",
                            PrecioUnitario = 15.99m,
                            ProveedorId = 2,
                            Stock = 60,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 2,
                            IsDeleted = false,
                            Nombre = "Pechuga de Pollo",
                            PrecioUnitario = 9.50m,
                            ProveedorId = 1,
                            Stock = 80,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            IsDeleted = false,
                            Nombre = "Muslo de Pollo",
                            PrecioUnitario = 7.99m,
                            ProveedorId = 1,
                            Stock = 75,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            IsDeleted = false,
                            Nombre = "Filete de Pescado",
                            PrecioUnitario = 16.50m,
                            ProveedorId = 2,
                            Stock = 40,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 3,
                            IsDeleted = false,
                            Nombre = "Jamón Serrano",
                            PrecioUnitario = 22.00m,
                            ProveedorId = 4,
                            Stock = 30,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 3,
                            IsDeleted = false,
                            Nombre = "Chorizo Español",
                            PrecioUnitario = 14.50m,
                            ProveedorId = 4,
                            Stock = 25,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 3,
                            IsDeleted = false,
                            Nombre = "Salchicha Premium",
                            PrecioUnitario = 12.75m,
                            ProveedorId = 4,
                            Stock = 45,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 4,
                            IsDeleted = false,
                            Nombre = "Camarón Fresco",
                            PrecioUnitario = 28.00m,
                            ProveedorId = 3,
                            Stock = 20,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 4,
                            IsDeleted = false,
                            Nombre = "Pulpo Gallego",
                            PrecioUnitario = 32.50m,
                            ProveedorId = 3,
                            Stock = 15,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 4,
                            IsDeleted = false,
                            Nombre = "Mejillones Frescos",
                            PrecioUnitario = 11.99m,
                            ProveedorId = 3,
                            Stock = 50,
                            Unidad = "kg"
                        });
                });

            modelBuilder.Entity("Service.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Ganadería Premium S.A."
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Distribuidora de Carnes del Sur"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Mariscos Frescos Ltda."
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Nombre = "Embutidos Artesanales"
                        });
                });

            modelBuilder.Entity("Service.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("tipoUsuarioEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Carlos Mendez",
                            tipoUsuarioEnum = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Ana González",
                            tipoUsuarioEnum = 1
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Juan Pérez",
                            tipoUsuarioEnum = 2
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Nombre = "María García",
                            tipoUsuarioEnum = 2
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Nombre = "Roberto López",
                            tipoUsuarioEnum = 2
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Nombre = "Sofía Martínez",
                            tipoUsuarioEnum = 1
                        });
                });

            modelBuilder.Entity("Service.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreClienteSinUsuario")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TipoPagoEnum")
                        .HasColumnType("int");

                    b.Property<int?>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 3,
                            Fecha = new DateTime(2025, 11, 18, 21, 21, 54, 561, DateTimeKind.Local).AddTicks(7952),
                            IsDeleted = false,
                            PrecioTotal = 76.50m,
                            TipoPagoEnum = 1,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 4,
                            Fecha = new DateTime(2025, 11, 20, 21, 21, 54, 561, DateTimeKind.Local).AddTicks(7985),
                            IsDeleted = false,
                            PrecioTotal = 57.49m,
                            TipoPagoEnum = 2,
                            VendedorId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 5,
                            Fecha = new DateTime(2025, 11, 23, 21, 21, 54, 561, DateTimeKind.Local).AddTicks(7990),
                            IsDeleted = false,
                            PrecioTotal = 94.99m,
                            TipoPagoEnum = 3,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 4,
                            Fecha = new DateTime(2025, 11, 24, 21, 21, 54, 561, DateTimeKind.Local).AddTicks(7994),
                            IsDeleted = false,
                            NombreClienteSinUsuario = "Cliente Anónimo",
                            PrecioTotal = 45.75m,
                            TipoPagoEnum = 4,
                            VendedorId = 2
                        });
                });

            modelBuilder.Entity("Service.Models.DetalleVenta", b =>
                {
                    b.HasOne("Service.Models.Producto", "producto")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Venta", "venta")
                        .WithMany("Items")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("producto");

                    b.Navigation("venta");
                });

            modelBuilder.Entity("Service.Models.Producto", b =>
                {
                    b.HasOne("Service.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Proveedor", "proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("proveedor");
                });

            modelBuilder.Entity("Service.Models.Venta", b =>
                {
                    b.HasOne("Service.Models.Usuarios", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Service.Models.Usuarios", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId");

                    b.Navigation("Cliente");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Service.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Service.Models.Producto", b =>
                {
                    b.Navigation("DetallesVenta");
                });

            modelBuilder.Entity("Service.Models.Venta", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
