// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(StockCarniceriaContext))]
    [Migration("20251005003742_DatosNuevos")]
    partial class DatosNuevos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Vacuno"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Aves"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Lácteos"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Nombre = "Bebidas"
                        });
                });

            modelBuilder.Entity("Service.Models.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdDetalleCompra")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DetallesCompra");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 30m,
                            FechaCompra = new DateTime(2025, 10, 4, 21, 37, 37, 535, DateTimeKind.Local).AddTicks(6516),
                            IdCompra = 0,
                            IdDetalleCompra = 0,
                            IsDeleted = false,
                            PrecioUnitario = 2000.00m,
                            ProductoId = 1,
                            ProveedorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 60m,
                            FechaCompra = new DateTime(2025, 10, 4, 21, 37, 37, 535, DateTimeKind.Local).AddTicks(6545),
                            IdCompra = 0,
                            IdDetalleCompra = 0,
                            IsDeleted = false,
                            PrecioUnitario = 1000.00m,
                            ProductoId = 2,
                            ProveedorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 25m,
                            FechaCompra = new DateTime(2025, 10, 4, 21, 37, 37, 535, DateTimeKind.Local).AddTicks(6551),
                            IdCompra = 0,
                            IdDetalleCompra = 0,
                            IsDeleted = false,
                            PrecioUnitario = 1500.00m,
                            ProductoId = 3,
                            ProveedorId = 3
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 50m,
                            FechaCompra = new DateTime(2025, 10, 4, 21, 37, 37, 535, DateTimeKind.Local).AddTicks(6556),
                            IdCompra = 0,
                            IdDetalleCompra = 0,
                            IsDeleted = false,
                            PrecioUnitario = 1200.00m,
                            ProductoId = 5,
                            ProveedorId = 2
                        });
                });

            modelBuilder.Entity("Service.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("IdDetalleVenta")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DetallesVenta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 2m,
                            IdDetalleVenta = 0,
                            IsDeleted = false,
                            PrecioUnitario = 2500.00m,
                            ProductoId = 1,
                            VentaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1m,
                            IdDetalleVenta = 0,
                            IsDeleted = false,
                            PrecioUnitario = 1500.00m,
                            ProductoId = 5,
                            VentaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 1m,
                            IdDetalleVenta = 0,
                            IsDeleted = false,
                            PrecioUnitario = 1200.00m,
                            ProductoId = 2,
                            VentaId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 2m,
                            IdDetalleVenta = 0,
                            IsDeleted = false,
                            PrecioUnitario = 900.00m,
                            ProductoId = 4,
                            VentaId = 2
                        });
                });

            modelBuilder.Entity("Service.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            IsDeleted = false,
                            Nombre = "Asado de Tira",
                            Precio = 2500.00m,
                            Stock = 20,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            IsDeleted = false,
                            Nombre = "Suprema de Pollo",
                            Precio = 1200.00m,
                            Stock = 40,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            IsDeleted = false,
                            Nombre = "Queso Cremoso",
                            Precio = 1800.00m,
                            Stock = 15,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            IsDeleted = false,
                            Nombre = "Leche Entera",
                            Precio = 900.00m,
                            Stock = 30,
                            Unidad = "litro"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 4,
                            IsDeleted = false,
                            Nombre = "Gaseosa Cola",
                            Precio = 1500.00m,
                            Stock = 50,
                            Unidad = "botella"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 1,
                            IsDeleted = false,
                            Nombre = "Matambre Vacuno",
                            Precio = 2200.00m,
                            Stock = 10,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 2,
                            IsDeleted = false,
                            Nombre = "Pechuga de Pollo",
                            Precio = 1300.00m,
                            Stock = 25,
                            Unidad = "kg"
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 3,
                            IsDeleted = false,
                            Nombre = "Yogur Natural",
                            Precio = 700.00m,
                            Stock = 35,
                            Unidad = "unidad"
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 4,
                            IsDeleted = false,
                            Nombre = "Agua Mineral",
                            Precio = 800.00m,
                            Stock = 60,
                            Unidad = "botella"
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 1,
                            IsDeleted = false,
                            Nombre = "Chorizo Parrillero",
                            Precio = 1100.00m,
                            Stock = 18,
                            Unidad = "kg"
                        });
                });

            modelBuilder.Entity("Service.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Frigorífico Patagonia"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Avícola San Juan"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Distribuidora Láctea SRL"
                        });
                });

            modelBuilder.Entity("Service.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@tienda.com",
                            IsDeleted = false,
                            Nombre = "Sofia",
                            Password = "sofiaAdmin2025",
                            Rol = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "carlos@tienda.com",
                            IsDeleted = false,
                            Nombre = "Carlos",
                            Password = "carlosV123",
                            Rol = "vendedor"
                        },
                        new
                        {
                            Id = 3,
                            Email = "lucia@tienda.com",
                            IsDeleted = false,
                            Nombre = "Lucia",
                            Password = "luciaV123",
                            Rol = "vendedor"
                        });
                });

            modelBuilder.Entity("Service.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TipoPagoEnum")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cliente = "Pedro López",
                            Fecha = new DateTime(2025, 10, 4, 21, 37, 37, 531, DateTimeKind.Local).AddTicks(1872),
                            IdVenta = 0,
                            IsDeleted = false,
                            Precio = 5000.00m,
                            TipoPagoEnum = 1,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            Cliente = "Laura Fernández",
                            Fecha = new DateTime(2025, 10, 4, 21, 37, 37, 531, DateTimeKind.Local).AddTicks(1897),
                            IdVenta = 0,
                            IsDeleted = false,
                            Precio = 2700.00m,
                            TipoPagoEnum = 2,
                            UsuarioId = 3
                        });
                });

            modelBuilder.Entity("Service.Models.Producto", b =>
                {
                    b.HasOne("Service.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
