// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(StockCarniceriaContext))]
    [Migration("20250912205850_actualizacion")]
    partial class actualizacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Carnes Rojas"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Carnes Blancas"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Embutidos"
                        });
                });

            modelBuilder.Entity("Service.Models.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdDetalleCompra")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DetallesCompra");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 20m,
                            FechaCompra = new DateTime(2025, 9, 12, 17, 58, 48, 260, DateTimeKind.Local).AddTicks(9052),
                            IdCompra = 0,
                            IdDetalleCompra = 0,
                            IsDeleted = false,
                            PrecioUnitario = 1200.00m,
                            ProductoId = 1,
                            ProveedorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 50m,
                            FechaCompra = new DateTime(2025, 9, 12, 17, 58, 48, 260, DateTimeKind.Local).AddTicks(9058),
                            IdCompra = 0,
                            IdDetalleCompra = 0,
                            IsDeleted = false,
                            PrecioUnitario = 700.00m,
                            ProductoId = 2,
                            ProveedorId = 2
                        });
                });

            modelBuilder.Entity("Service.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("IdDetalleVenta")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DetallesVenta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 2m,
                            IdDetalleVenta = 0,
                            IsDeleted = false,
                            PrecioUnitario = 1500.00m,
                            ProductoId = 1,
                            VentaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1m,
                            IdDetalleVenta = 0,
                            IsDeleted = false,
                            PrecioUnitario = 800.00m,
                            ProductoId = 2,
                            VentaId = 2
                        });
                });

            modelBuilder.Entity("Service.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            IdProducto = 0,
                            IsDeleted = false,
                            Nombre = "Bife de Chorizo",
                            Precio = 1500.00m,
                            ProveedorId = 1,
                            Stock = 50,
                            Unidad = ""
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            IdProducto = 0,
                            IsDeleted = false,
                            Nombre = "Pechuga de Pollo",
                            Precio = 800.00m,
                            ProveedorId = 2,
                            Stock = 100,
                            Unidad = ""
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            IdProducto = 0,
                            IsDeleted = false,
                            Nombre = "Chorizo",
                            Precio = 400.00m,
                            ProveedorId = 1,
                            Stock = 200,
                            Unidad = ""
                        });
                });

            modelBuilder.Entity("Service.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Proveedor A"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Proveedor B"
                        });
                });

            modelBuilder.Entity("Service.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@carniceria.com",
                            IsDeleted = false,
                            Nombre = "Martin",
                            Password = "admin123",
                            Rol = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "vendedor1@carniceria.com",
                            IsDeleted = false,
                            Nombre = "Pepe",
                            Password = "vendedor123",
                            Rol = "vendedor"
                        });
                });

            modelBuilder.Entity("Service.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TipoPagoEnum")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cliente = "Juan Perez",
                            Fecha = new DateTime(2025, 9, 12, 17, 58, 48, 260, DateTimeKind.Local).AddTicks(8903),
                            IdVenta = 0,
                            IsDeleted = false,
                            Precio = 3000.00m,
                            TipoPagoEnum = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cliente = "Maria Gomez",
                            Fecha = new DateTime(2025, 9, 12, 17, 58, 48, 260, DateTimeKind.Local).AddTicks(8925),
                            IdVenta = 0,
                            IsDeleted = false,
                            Precio = 800.00m,
                            TipoPagoEnum = 3,
                            UsuarioId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
